### ISSUE TITLE
1.3 - Pluggable renderer

### ISSUE THREAD

**Issue by Madman10K** [MadLadSquad/UntitledImGuiFramework#1580]
The current rendering setup is as minimal as possible. The idea is to have a renderer that is good enough to be used by just dear imgui. This is fine for most use cases. Even for applications that require custom rendering, most of them are going to work with imgui's draw list API, which is supported.

However, this approach does not work when one needs multiple pipelines for their application.

This is where the pluggable renderer will help. It will allow for users to easily integrate a custom rendering solution into their application.

## Changes to `Renderer.yaml`
To allow for a custom renderer, we decided to implemented a number of changes in `Renderer.yaml`. The `vulkan: ` key will be replaced by `renderer: ` which can be one of `opengl`, `vulkan`, `custom`. When set to custom the `custom-renderer:` field can also be available to be parsed manually by the developer. For example:
```yaml
renderer: custom              # One of "opengl", "vulkan" or `custom`
v-sync: true                  # To run or not to run in V-Sync mode
msaa-samples: 8               # Multisampling sample count
power-saving:                 # The power saving mode limits the number of frames that are drawn when idling. Will not work for applications with live plots or animations
  enabled: true
  idle-frames: 9
custom-renderer:
  shader-detail: 2
  debug-mode: true
```

## Changes to the build system
One can enable the following options to build the following dear imgui backends:

1. `IMGUI_BUILD_WITH_DX11`
1. `IMGUI_BUILD_WITH_DX12`
1. `IMGUI_BUILD_WITH_METAL`

The OpenGL, Vulkan and WebGPU backends are always going to be compiled with your application.

> [!NOTE]
> The `IMGUI_BUILD_WITH_METAL` option will be enabled by default for system-wide builds on macOS

## Changes to the user-facing code
In the constructor of the `Instance`, we'll allow for the user to add a callback that sets up the renderer and registers it with the renderer adapter. This will then allow for plugging into the configuration system and starting of the renderer itself.

Custom renderer objects will be able to be created by deriving the existing `GenericRenderer` class.

## Changes to the C API
New functions will be added to allow users to spawn custom renderers. The design will closely mirror the current C implementations of UI components.

## Tasks
TODO:

- Config:
  - [x] Change the config to support custom renderers
  - [x] Integrate the new config in the framework
  - [x] Document

- Querying renderer/platform capabilities and requirements:
  - [x] Open up checks for whether we support WebGPU
  - [x] Setup custom OpenGL context
    - [x] Set OpenGL version
    - [x] Set OpenGL standard
    - [x] Set OpenGL compatibility
    - [x] Set OpenGL profile
    - [x] Add a platform function for swapping buffers
    - [x] Create a C API
    - [x] Document API
  - [x] Set up without an API
  - [x] Raw window access
    - [x] Add easy access to the raw window handle
    - [x] Make sure users have the native windowing library included
    - [x] Create a C API
    - [x] Document

- Registering custom renderers
  - [x] Registration
    - [x] Refactor renderer selection
    - [x] Add a way to select the current renderer and change it if it's custom during application startup
    - [x] Add a C API
    - [x] Document
  - [x] Configuration
    - [x] Give a parse callback with a reference to the custom rendering config object
    - [x] Give an output callback
    - [x] Document

- Textures
  - [x] Separate renderer backend type from texture backend type(for example if the custom renderer is OpenGL, one can decide to reuse the OpenGL texture backend)
  - [x] Set a texture backend
  - [x] C API
  - [x] Document

- Build
  - [x] macOS: build with the metal backends and API enabled by default
  - [x] Windows: allow for enabling DX11 or DX12 backends and APIs
  - [x] Document options

- Examples
  - [x] Create a basic OpenGL example
  - [x] Create a basic Vulkan example
  - [x] Create a basic WebGPU example
  - [x] Create a bgfx example

- Post-release
  - [x] Refactor the way the renderer, window, global, etc are initialised and started. Needed to improve readability and internal code navigation.
  - [x] Document
